# Model hyperparameters

MODEL_TRAINER:
  classification:
    epochs: 10
    batch_size: 32
    image_size: [224, 224]
    learning_rate: 0.001
    include_top: false
    weights: imagenet
  detection:
    epochs: 50
    batch_size: 16
    image_size: 640
    pretrained_weights: yolov8n.pt

CUSTOM_CNN:
  input_shape: [224, 224, 3]
  num_classes: 2
  dropout_rate: 0.3
  
TRANSFER_LEARNING:
  models: ['resnet50', 'mobilenet', 'efficientnetb0']
  freeze_layers: true
  fine_tune_layers: 10
  
YOLOV8:
  model_size: 'n'  # n, s, m, l, x
  conf_threshold: 0.25
  iou_threshold: 0.45
  max_det: 300
  
DATA_AUGMENTATION:
  rotation_range: 20
  width_shift_range: 0.2
  height_shift_range: 0.2
  horizontal_flip: true
  zoom_range: 0.2
  brightness_range: [0.8, 1.2]