# schema.yaml
CLASSIFICATION_DATA:
  required_classes:
    - bird
    - drone
  required_splits:
    - train
    - valid
    - test
  image_extensions:
    - .jpg
    - .jpeg
    - .png
    - .bmp

DETECTION_DATA:
  required_directories:
    - train/images
    - train/labels
    - valid/images
    - valid/labels
    - test/images
    - test/labels
  required_files:
    - data.yaml
  expected_classes:
    - Bird
    - drone